/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.spbstu.j23.dto;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        assertTrue(true);
    }
}
